server:
  port: 20000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 'chensj7612'
    driver-class-name: com.mysql.cj.jdbc.Driver

resources:
    static-locations=/WEB-INF/resources/:
mybatis:
    mapper-locations: classpath:dao/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.example.demo.bean  # 注意：对应实体类的路径


